import type { Profile, StyleRule } from "../schema/index.js";
import type { GeneratedFile } from "./types.js";

interface EslintRuleEntry {
  plugin: string;
  rule: string;
  severity: "error" | "warn" | "off";
  options?: unknown[];
}

const CATEGORY_KEYS = [
  "naming",
  "structure",
  "documentation",
  "errorHandling",
  "formatting",
  "patterns",
] as const;

function severityForConfidence(
  confidence: number,
  thresholds: Profile["severityThresholds"],
): "error" | "warn" | "off" | null {
  if (confidence >= thresholds.error) return "error";
  if (confidence >= thresholds.warn) return "warn";
  if (confidence >= thresholds.info) return "off";
  return null;
}

function collectEslintExtensions(profile: Profile): EslintRuleEntry[] {
  const entries: EslintRuleEntry[] = [];
  const thresholds = profile.severityThresholds;

  for (const category of CATEGORY_KEYS) {
    const section = profile[category];
    if (!section) continue;

    for (const [, rule] of Object.entries(section as Record<string, StyleRule>)) {
      if (!rule.extensions?.eslint) continue;

      const ext = rule.extensions.eslint as {
        rule: string;
        options?: unknown[];
      };

      const sev = severityForConfidence(rule.confidence, thresholds);
      if (sev === null) continue;

      const plugin = ext.rule.includes("/")
        ? ext.rule.split("/").slice(0, -1).join("/")
        : "";

      entries.push({
        plugin,
        rule: ext.rule,
        severity: sev === "off" ? "warn" : sev,
        options: ext.options,
      });
    }
  }

  return entries;
}

function addImportOrderRule(profile: Profile, entries: EslintRuleEntry[]): void {
  const importOrder = profile.structure?.importOrder;
  if (!importOrder) return;

  const sev = severityForConfidence(
    importOrder.confidence,
    profile.severityThresholds,
  );
  if (!sev || sev === "off") return;

  entries.push({
    plugin: "perfectionist",
    rule: "perfectionist/sort-imports",
    severity: sev,
    options: [{ groups: importOrder.convention }],
  });
}

function detectRequiredPlugins(entries: EslintRuleEntry[]): Set<string> {
  const plugins = new Set<string>();
  for (const entry of entries) {
    if (entry.plugin.includes("@typescript-eslint")) {
      plugins.add("@typescript-eslint");
    }
    if (entry.plugin === "perfectionist") {
      plugins.add("perfectionist");
    }
    if (entry.plugin.includes("unicorn")) {
      plugins.add("unicorn");
    }
    if (entry.plugin.includes("jsdoc")) {
      plugins.add("jsdoc");
    }
  }
  return plugins;
}

function generateImportStatements(plugins: Set<string>): string[] {
  const imports: string[] = [];
  if (plugins.has("@typescript-eslint")) {
    imports.push(`import tseslint from "@typescript-eslint/eslint-plugin";`);
    imports.push(`import tsparser from "@typescript-eslint/parser";`);
  }
  if (plugins.has("perfectionist")) {
    imports.push(`import perfectionist from "eslint-plugin-perfectionist";`);
  }
  if (plugins.has("unicorn")) {
    imports.push(`import unicorn from "eslint-plugin-unicorn";`);
  }
  if (plugins.has("jsdoc")) {
    imports.push(`import jsdoc from "eslint-plugin-jsdoc";`);
  }
  return imports;
}

function buildRulesObject(
  entries: EslintRuleEntry[],
): Record<string, unknown> {
  const rules: Record<string, unknown> = {};
  for (const entry of entries) {
    if (entry.options && entry.options.length > 0) {
      rules[entry.rule] = [entry.severity, ...entry.options];
    } else {
      rules[entry.rule] = entry.severity;
    }
  }
  return rules;
}

export function generateEslintExport(profile: Profile): GeneratedFile {
  const entries = collectEslintExtensions(profile);
  addImportOrderRule(profile, entries);

  const plugins = detectRequiredPlugins(entries);
  const imports = generateImportStatements(plugins);
  const rules = buildRulesObject(entries);

  const header = [
    `// Generated by code-style for ${profile.author}`,
    `// Date: ${profile.generated}`,
    `// Do not edit manually - regenerate with: code-style export --format eslint`,
    "",
  ].join("\n");

  const content = [
    header,
    ...imports,
    "",
    `export default ${JSON.stringify({ rules }, null, 2)};`,
    "",
  ].join("\n");

  return { path: "eslint.config.js", content };
}
