import { readFile } from "node:fs/promises"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"
import { describe, it, expect, beforeAll } from "vitest"
import { ProfileSchema } from "../../../packages/profile/src/schema/profile.js"
import { generateEditorConfigExport } from "../../../packages/profile/src/exporters/editorconfig.js"
import type { Profile } from "../../../packages/profile/src/schema/profile.js"

const __dirname = dirname(fileURLToPath(import.meta.url))

const FIXTURE_PATH = join(
  __dirname,
  "../fixtures/exports/test-profile.json",
)

function parseEditorConfig(
  content: string,
): Record<string, Record<string, string>> {
  const sections: Record<string, Record<string, string>> = {}
  let currentSection = "__root__"
  sections[currentSection] = {}

  for (const line of content.split("\n")) {
    const trimmed = line.trim()
    if (trimmed === "" || trimmed.startsWith("#")) continue

    const sectionMatch = trimmed.match(/^\[(.+)]$/)
    if (sectionMatch) {
      currentSection = sectionMatch[1]
      sections[currentSection] = {}
      continue
    }

    const kvMatch = trimmed.match(/^([^=]+?)\s*=\s*(.+)$/)
    if (kvMatch) {
      sections[currentSection][kvMatch[1].trim()] = kvMatch[2].trim()
    }
  }

  return sections
}

describe("EditorConfig generation", () => {
  let profile: Profile
  let content: string
  let parsed: Record<string, Record<string, string>>

  beforeAll(async () => {
    const raw = await readFile(FIXTURE_PATH, "utf-8")
    profile = ProfileSchema.parse(JSON.parse(raw))
    const exported = generateEditorConfigExport(profile)
    expect(exported.path).toBe(".editorconfig")
    content = exported.content
    parsed = parseEditorConfig(content)
  })

  it("outputs .editorconfig path", () => {
    const exported = generateEditorConfigExport(profile)
    expect(exported.path).toBe(".editorconfig")
  })

  it("sets root = true", () => {
    expect(parsed["__root__"]["root"]).toBe("true")
  })

  it("contains indent_style when profile specifies indentStyle", () => {
    const globalSection = parsed["*"]
    expect(globalSection).toBeDefined()

    const profileIndentStyle = profile.formatting?.indentStyle
    if (profileIndentStyle) {
      expect(globalSection["indent_style"]).toBeDefined()
      const convention = profileIndentStyle.convention
      if (convention === "spaces") {
        expect(globalSection["indent_style"]).toBe("space")
      } else if (convention === "tabs") {
        expect(globalSection["indent_style"]).toBe("tab")
      }
    }
  })

  it("contains end_of_line", () => {
    const globalSection = parsed["*"]
    expect(globalSection).toBeDefined()
    expect(globalSection["end_of_line"]).toBeDefined()
  })

  it("contains charset", () => {
    const globalSection = parsed["*"]
    expect(globalSection).toBeDefined()
    expect(globalSection["charset"]).toBe("utf-8")
  })

  it("contains indent_size when profile specifies it", () => {
    const globalSection = parsed["*"]
    const profileIndentSize = profile.formatting?.indentSize
    if (profileIndentSize !== undefined) {
      expect(globalSection["indent_size"]).toBe(
        String(profileIndentSize.convention),
      )
    }
  })

  it("contains max_line_length when profile specifies it", () => {
    const globalSection = parsed["*"]
    const profileLineLength = profile.formatting?.lineLength
    if (profileLineLength !== undefined) {
      expect(globalSection["max_line_length"]).toBe(
        String(profileLineLength.convention),
      )
    }
  })

  it("includes generation comment", () => {
    expect(content).toContain("Generated by codewatch")
  })
})
