import { readFile } from "node:fs/promises"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"
import { describe, it, expect, beforeAll } from "vitest"
import { ProfileSchema } from "../../../packages/profile/src/schema/profile.js"
import { generateEslintExport } from "../../../packages/profile/src/exporters/eslint.js"
import { generateEslintConfig } from "../../../packages/checker/src/generators/eslint.js"
import type { Profile } from "../../../packages/profile/src/schema/profile.js"
import type { EslintFlatConfigEntry } from "../../../packages/checker/src/generators/eslint.js"

const __dirname = dirname(fileURLToPath(import.meta.url))

const FIXTURE_PATH = join(
  __dirname,
  "../fixtures/exports/test-profile.json",
)

describe("ESLint config generation", () => {
  let profile: Profile
  let configEntries: EslintFlatConfigEntry[]

  beforeAll(async () => {
    const raw = await readFile(FIXTURE_PATH, "utf-8")
    profile = ProfileSchema.parse(JSON.parse(raw))
  })

  describe("generateEslintConfig (checker)", () => {
    beforeAll(() => {
      configEntries = generateEslintConfig(profile)
    })

    it("returns non-empty config entries", () => {
      expect(configEntries.length).toBeGreaterThan(0)
    })

    it("contains naming convention rule", () => {
      const allRules = configEntries.flatMap((entry) =>
        Object.keys(entry.rules ?? {}),
      )
      expect(allRules).toContainEqual(
        expect.stringMatching(/@typescript-eslint\/naming-convention/),
      )
    })

    it("contains import ordering rule", () => {
      const allRules = configEntries.flatMap((entry) =>
        Object.keys(entry.rules ?? {}),
      )
      expect(allRules).toContainEqual(
        expect.stringMatching(/import/),
      )
    })

    it("targets TypeScript files", () => {
      const hasTypeScriptFiles = configEntries.some((entry) =>
        entry.files?.some((f) => f.includes(".ts")),
      )
      expect(hasTypeScriptFiles).toBe(true)
    })
  })

  describe("generateEslintExport (profile)", () => {
    it("generates eslint.config.js file", () => {
      const exported = generateEslintExport(profile)
      expect(exported.path).toBe("eslint.config.js")
      expect(exported.content.length).toBeGreaterThan(0)
    })

    it("contains import statements for required plugins", () => {
      const exported = generateEslintExport(profile)
      const content = exported.content

      expect(content).toContain("export default")

      if (profile.naming && Object.keys(profile.naming).length > 0) {
        const hasPluginImport =
          content.includes("@typescript-eslint") ||
          content.includes("perfectionist") ||
          content.includes("eslint-plugin")
        expect(hasPluginImport).toBe(true)
      }
    })

    it("contains rules matching the profile", () => {
      const exported = generateEslintExport(profile)
      const content = exported.content

      expect(content).toContain("rules")
    })

    it("is parseable JavaScript", () => {
      const exported = generateEslintExport(profile)
      const content = exported.content

      const openBraces = (content.match(/{/g) ?? []).length
      const closeBraces = (content.match(/}/g) ?? []).length
      expect(openBraces).toBe(closeBraces)

      const openBrackets = (content.match(/\[/g) ?? []).length
      const closeBrackets = (content.match(/]/g) ?? []).length
      expect(openBrackets).toBe(closeBrackets)
    })

    it("includes generation metadata comment", () => {
      const exported = generateEslintExport(profile)
      expect(exported.content).toContain("Generated by code-style")
    })
  })
})
